import json
from pathlib import Path

import torch

from app.models.gat_model import GATNetwork


class GATInference:
    """
    GAT inference engine.

    Supports:
    1. Inference using the original training graph.
    2. Inference using a live graph generated by LiveGraphBuilder.
    """

    def __init__(
        self,
        model_path="trained_models/gat/gat_model_leakage_safe.pt",
        threshold_path="trained_models/gat/gat_threshold.json",
        graph_path="data/gat/gat_graph_leakage_safe.pt",
        device=None
    ):

        self.model_path = Path(model_path)
        self.threshold_path = Path(threshold_path)
        self.graph_path = Path(graph_path)

        # =========================================================
        # DEVICE
        # =========================================================
        if device is None:
            self.device = torch.device(
                "cuda" if torch.cuda.is_available() else "cpu"
            )
        else:
            self.device = torch.device(device)

        # =========================================================
        # LOAD CHECKPOINT
        # =========================================================
        self.checkpoint = torch.load(
            self.model_path,
            map_location=self.device,
            weights_only=False
        )

        # =========================================================
        # MODEL CONFIGURATION
        # =========================================================
        self.input_dim = self.checkpoint["input_dim"]
        self.hidden_dim = self.checkpoint["hidden_dim"]
        self.heads = self.checkpoint["heads"]
        self.dropout = self.checkpoint["dropout"]

        # =========================================================
        # CREATE MODEL
        # =========================================================
        self.model = GATNetwork(
            input_dim=self.input_dim,
            hidden_dim=self.hidden_dim,
            heads=self.heads,
            dropout=self.dropout
        )

        # =========================================================
        # LOAD TRAINED WEIGHTS
        # =========================================================
        self.model.load_state_dict(
            self.checkpoint["model_state_dict"]
        )

        self.model.to(self.device)
        self.model.eval()

        # =========================================================
        # TRAINING NORMALIZATION STATISTICS
        # =========================================================
        self.feature_mean = (
            self.checkpoint["feature_mean"]
            .to(self.device)
        )

        self.feature_std = (
            self.checkpoint["feature_std"]
            .to(self.device)
        )

        self.feature_names = (
            self.checkpoint["feature_names"]
        )

        # =========================================================
        # LOAD DETECTION THRESHOLD
        # =========================================================
        with open(self.threshold_path, "r") as file:
            threshold_data = json.load(file)

        self.threshold = float(
            threshold_data["threshold"]
        )

        # =========================================================
        # LOAD TRAINING GRAPH
        # =========================================================
        self.graph = torch.load(
            self.graph_path,
            map_location="cpu",
            weights_only=False
        )

        self.graph_x = self.graph["x"].to(
            self.device
        )

        self.graph_edge_index = (
            self.graph["edge_index"].to(
                self.device
            )
        )

        # =========================================================
        # NORMALIZE IP MAPPING
        # =========================================================
        self.index_to_ip = self._normalize_ip_mapping(
            self.graph["index_to_ip"]
        )

        self.ip_to_index = {
            ip: index
            for index, ip in enumerate(
                self.index_to_ip
            )
        }

        # =========================================================
        # INFORMATION
        # =========================================================
        print("=" * 70)
        print("GAT INFERENCE ENGINE")
        print("=" * 70)

        print(
            f"Device:              {self.device}"
        )

        print(
            f"Input features:      {self.input_dim}"
        )

        print(
            f"Hidden dimension:    {self.hidden_dim}"
        )

        print(
            f"Attention heads:     {self.heads}"
        )

        print(
            f"Graph nodes:         {self.graph['num_nodes']}"
        )

        print(
            f"Graph edges:         {self.graph['num_edges']}"
        )

        print(
            f"Detection threshold: {self.threshold}"
        )

        print("=" * 70)

    # =============================================================
    # NORMALIZE IP MAPPING
    # =============================================================
    @staticmethod
    def _normalize_ip_mapping(mapping):
        """
        Convert different possible index_to_ip formats
        into a simple list:

            index -> IP

        Example:

            [
                "0.0.0.0",
                "0.40.115.17",
                ...
            ]
        """

        # ---------------------------------------------------------
        # Already a list / tuple
        # ---------------------------------------------------------
        if isinstance(mapping, (list, tuple)):

            return list(mapping)

        # ---------------------------------------------------------
        # Tensor
        # ---------------------------------------------------------
        if torch.is_tensor(mapping):

            return mapping.tolist()

        # ---------------------------------------------------------
        # Dictionary
        # ---------------------------------------------------------
        if isinstance(mapping, dict):

            items = list(mapping.items())

            if not items:
                return []

            # -----------------------------------------------------
            # Case 1:
            #
            # {
            #     0: "0.0.0.0",
            #     1: "0.40.115.17"
            # }
            # -----------------------------------------------------
            try:

                numeric_keys = all(
                    isinstance(key, int)
                    or (
                        isinstance(key, str)
                        and key.strip().lstrip("-").isdigit()
                    )
                    for key, _ in items
                )

                if numeric_keys:

                    sorted_items = sorted(
                        items,
                        key=lambda item: int(item[0])
                    )

                    return [
                        value
                        for _, value in sorted_items
                    ]

            except (ValueError, TypeError):
                pass

            # -----------------------------------------------------
            # Case 2:
            #
            # {
            #     "0.0.0.0": 0,
            #     "0.40.115.17": 1
            # }
            # -----------------------------------------------------
            try:

                numeric_values = all(
                    isinstance(value, int)
                    or (
                        isinstance(value, str)
                        and value.strip().lstrip("-").isdigit()
                    )
                    for _, value in items
                )

                if numeric_values:

                    sorted_items = sorted(
                        items,
                        key=lambda item: int(item[1])
                    )

                    return [
                        key
                        for key, _ in sorted_items
                    ]

            except (ValueError, TypeError):
                pass

        raise TypeError(
            "Unsupported index_to_ip format: "
            f"{type(mapping)}"
        )

    # =============================================================
    # NORMALIZE FEATURES
    # =============================================================
    def _normalize_features(self, x):

        return (
            x - self.feature_mean
        ) / self.feature_std

    # =============================================================
    # TRAINING GRAPH EMBEDDINGS
    # =============================================================
    @torch.no_grad()
    def _get_embeddings(self):

        x = self.graph_x

        x = self._normalize_features(x)

        _, embeddings = self.model(
            x,
            self.graph_edge_index,
            self.graph_edge_index
        )

        return embeddings

    # =============================================================
    # PREDICT ONE EDGE FROM TRAINING GRAPH
    # =============================================================
    @torch.no_grad()
    def predict_edge(
        self,
        source_ip,
        destination_ip
    ):

        # ---------------------------------------------------------
        # SOURCE IP
        # ---------------------------------------------------------
        if source_ip not in self.ip_to_index:

            return {
                "source_ip": source_ip,
                "destination_ip": destination_ip,
                "attack_score": 0.0,
                "is_anomaly": False,
                "threshold": self.threshold,
                "status": "source_ip_not_found"
            }

        # ---------------------------------------------------------
        # DESTINATION IP
        # ---------------------------------------------------------
        if destination_ip not in self.ip_to_index:

            return {
                "source_ip": source_ip,
                "destination_ip": destination_ip,
                "attack_score": 0.0,
                "is_anomaly": False,
                "threshold": self.threshold,
                "status": "destination_ip_not_found"
            }

        source_index = self.ip_to_index[
            source_ip
        ]

        destination_index = self.ip_to_index[
            destination_ip
        ]

        # ---------------------------------------------------------
        # NODE EMBEDDINGS
        # ---------------------------------------------------------
        embeddings = self._get_embeddings()

        source_embedding = embeddings[
            source_index
        ]

        destination_embedding = embeddings[
            destination_index
        ]

        # ---------------------------------------------------------
        # EDGE REPRESENTATION
        # ---------------------------------------------------------
        edge_representation = torch.cat(
            [
                source_embedding,
                destination_embedding
            ],
            dim=0
        ).unsqueeze(0)

        # ---------------------------------------------------------
        # CLASSIFICATION
        # ---------------------------------------------------------
        logits = self.model.edge_classifier(
            edge_representation
        )

        probabilities = torch.softmax(
            logits,
            dim=1
        )

        attack_score = float(
            probabilities[0, 1].item()
        )

        is_anomaly = (
            attack_score >= self.threshold
        )

        return {
            "source_ip": source_ip,
            "destination_ip": destination_ip,
            "attack_score": attack_score,
            "is_anomaly": is_anomaly,
            "threshold": self.threshold,
            "status": "success"
        }

    # =============================================================
    # PREDICT MULTIPLE EDGES
    # =============================================================
    def predict_edges(self, edges):

        results = []

        for edge in edges:

            result = self.predict_edge(
                source_ip=edge["source_ip"],
                destination_ip=edge["destination_ip"]
            )

            results.append(result)

        return results

    # =============================================================
    # PREDICT ALL EDGES IN LIVE GRAPH
    # =============================================================
    @torch.no_grad()
    def predict_live_graph(self, graph):

        if graph is None:
            return []

        # ---------------------------------------------------------
        # LIVE NODE FEATURES
        # ---------------------------------------------------------
        x = graph["x"].to(
            self.device
        )

        # ---------------------------------------------------------
        # LIVE EDGES
        # ---------------------------------------------------------
        edge_index = graph["edge_index"].to(
            self.device
        )

        # ---------------------------------------------------------
        # EMPTY GRAPH
        # ---------------------------------------------------------
        if edge_index.shape[1] == 0:
            return []

        # ---------------------------------------------------------
        # FEATURE VALIDATION
        # ---------------------------------------------------------
        if x.shape[1] != self.input_dim:

            raise ValueError(
                f"Live graph has {x.shape[1]} features, "
                f"but GAT expects {self.input_dim}."
            )

        # ---------------------------------------------------------
        # NORMALIZE
        # ---------------------------------------------------------
        x = self._normalize_features(x)

        # ---------------------------------------------------------
        # GAT MESSAGE PASSING
        # ---------------------------------------------------------
        _, embeddings = self.model(
            x,
            edge_index,
            edge_index
        )

        # ---------------------------------------------------------
        # SOURCE / DESTINATION
        # ---------------------------------------------------------
        source_nodes = edge_index[0]

        destination_nodes = edge_index[1]

        # ---------------------------------------------------------
        # EMBEDDINGS
        # ---------------------------------------------------------
        source_embeddings = embeddings[
            source_nodes
        ]

        destination_embeddings = embeddings[
            destination_nodes
        ]

        # ---------------------------------------------------------
        # EDGE REPRESENTATIONS
        # ---------------------------------------------------------
        edge_representations = torch.cat(
            [
                source_embeddings,
                destination_embeddings
            ],
            dim=1
        )

        # ---------------------------------------------------------
        # EDGE CLASSIFIER
        # ---------------------------------------------------------
        logits = self.model.edge_classifier(
            edge_representations
        )

        probabilities = torch.softmax(
            logits,
            dim=1
        )

        attack_scores = probabilities[:, 1]

        # ---------------------------------------------------------
        # LIVE IP LIST
        # ---------------------------------------------------------
        index_to_ip = graph["index_to_ip"]

        # ---------------------------------------------------------
        # PREDICTIONS
        # ---------------------------------------------------------
        results = []

        for i in range(
            edge_index.shape[1]
        ):

            source_index = int(
                source_nodes[i].item()
            )

            destination_index = int(
                destination_nodes[i].item()
            )

            attack_score = float(
                attack_scores[i].item()
            )

            is_anomaly = (
                attack_score >= self.threshold
            )

            results.append({
                "source_ip": index_to_ip[
                    source_index
                ],
                "destination_ip": index_to_ip[
                    destination_index
                ],
                "attack_score": attack_score,
                "is_anomaly": is_anomaly,
                "threshold": self.threshold,
                "status": "success"
            })

        return results


# =================================================================
# TEST
# =================================================================
if __name__ == "__main__":

    from app.graph.live_graph_builder import (
        LiveGraphBuilder
    )

    # -------------------------------------------------------------
    # CREATE GAT INFERENCE ENGINE
    # -------------------------------------------------------------
    detector = GATInference()

    # -------------------------------------------------------------
    # CREATE LIVE GRAPH BUILDER
    # -------------------------------------------------------------
    builder = LiveGraphBuilder()

    # -------------------------------------------------------------
    # TEST FLOWS
    # -------------------------------------------------------------
    test_flows = [

        {
            "source_ip": "192.168.1.10",
            "destination_ip": "8.8.8.8",
            "protocol": "UDP",
            "packet_count": 10,
            "byte_count": 1000,
            "duration": 1.0,
            "packets_per_second": 10.0,
            "bytes_per_second": 1000.0,
            "average_packet_size": 100.0
        },

        {
            "source_ip": "192.168.1.10",
            "destination_ip": "1.1.1.1",
            "protocol": "TCP",
            "packet_count": 5,
            "byte_count": 500,
            "duration": 2.0,
            "packets_per_second": 2.5,
            "bytes_per_second": 250.0,
            "average_packet_size": 100.0
        }
    ]

    # -------------------------------------------------------------
    # BUILD LIVE GRAPH
    # -------------------------------------------------------------
    live_graph = builder.build(
        test_flows
    )

    print("\n")
    print("=" * 70)
    print("LIVE GAT INFERENCE TEST")
    print("=" * 70)

    print(
        f"Live nodes:      {live_graph['num_nodes']}"
    )

    print(
        f"Live edges:      {live_graph['num_edges']}"
    )

    print(
        f"Feature shape:   {live_graph['x'].shape}"
    )

    print(
        f"Edge shape:      {live_graph['edge_index'].shape}"
    )

    # -------------------------------------------------------------
    # RUN LIVE INFERENCE
    # -------------------------------------------------------------
    results = detector.predict_live_graph(
        live_graph
    )

    print("\n")
    print("=" * 70)
    print("LIVE PREDICTIONS")
    print("=" * 70)

    for result in results:

        print("\n" + "-" * 70)

        print(
            f"Source IP:        "
            f"{result['source_ip']}"
        )

        print(
            f"Destination IP:   "
            f"{result['destination_ip']}"
        )

        print(
            f"Attack score:     "
            f"{result['attack_score']:.4f}"
        )

        print(
            f"Threshold:        "
            f"{result['threshold']:.2f}"
        )

        print(
            f"Prediction:       "
            f"{'ATTACK' if result['is_anomaly'] else 'BENIGN'}"
        )

        print(
            f"Status:           "
            f"{result['status']}"
        )

    print("\n")
    print("=" * 70)
    print("LIVE GAT INFERENCE TEST COMPLETE")
    print("=" * 70)